matlab_raw_file: data/nips12raw_str602.mat
idx_files: 
  - data/nipstxt/idx/a00.txt
  - data/nipstxt/idx/a01.txt
  - data/nipstxt/idx/a02.txt
  - data/nipstxt/idx/a03.txt
  - data/nipstxt/idx/a04.txt

author_map: data/authors_group.csv

weight_type:
  - direct
  - indirect

weight_conf:
  alpha: 0.8

