matlab_raw_file: data/nips12raw_str602.mat
idx_files: data/nipstxt/idx/a*.txt

author_map: data/authors_group.csv

weight_type:
  - direct
  - indirect
  - interact

weight_conf:
  alpha: 0.8
  beta: 1.0


